// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma Migrate/CLI usa esta URL (deve ser a conexão direta, não-pooled).
    // O runtime da aplicação (lib/prisma.ts) usa DATABASE_URL separadamente via driver adapter.
    url: env("DIRECT_URL"),
  },
});
